import type {
  DashboardMetrics,
  RetentionAlert,
  ChurnEvent,
  RevenueRecoveryItem,
  AIInsight,
  RevenueDataPoint,
  MemberActivity,
} from '@/types';

export const mockMetrics: DashboardMetrics = {
  totalRevenue: 148320,
  revenueChange: 12.4,
  activeMembers: 2847,
  membersChange: 8.1,
  churnRate: 3.2,
  churnChange: -0.8,
  recoveredRevenue: 14200,
  recoveredChange: 34.5,
  mrr: 38400,
  mrrChange: 9.2,
  ltv: 284,
};

export const mockRetentionAlerts: RetentionAlert[] = [
  {
    id: '1',
    userId: 'usr_001',
    userName: 'Alex Martinez',
    riskLevel: 'critical',
    riskScore: 94,
    reason: 'No login in 21 days, payment failed once',
    daysInactive: 21,
    memberSince: '2024-03-15',
    plan: 'Elite Mastermind',
    planValue: 297,
    lastActivity: new Date(Date.now() - 21 * 86400000).toISOString(),
  },
  {
    id: '2',
    userId: 'usr_002',
    userName: 'Sarah Chen',
    riskLevel: 'critical',
    riskScore: 89,
    reason: 'Opened cancellation page 3 times this week',
    daysInactive: 14,
    memberSince: '2024-01-08',
    plan: 'Pro Course Bundle',
    planValue: 197,
    lastActivity: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: '3',
    userId: 'usr_003',
    userName: 'James Wilson',
    riskLevel: 'high',
    riskScore: 76,
    reason: 'Engagement dropped 80% vs last month',
    daysInactive: 9,
    memberSince: '2024-05-22',
    plan: 'Monthly Access',
    planValue: 97,
    lastActivity: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
  {
    id: '4',
    userId: 'usr_004',
    userName: 'Priya Patel',
    riskLevel: 'high',
    riskScore: 71,
    reason: 'Submitted support ticket about value',
    daysInactive: 6,
    memberSince: '2024-06-10',
    plan: 'Elite Mastermind',
    planValue: 297,
    lastActivity: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: '5',
    userId: 'usr_005',
    userName: 'Marcus Thompson',
    riskLevel: 'medium',
    riskScore: 55,
    reason: 'Course completion rate below 20%',
    daysInactive: 4,
    memberSince: '2024-07-01',
    plan: 'Pro Course Bundle',
    planValue: 197,
    lastActivity: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: '6',
    userId: 'usr_006',
    userName: 'Luna Rodriguez',
    riskLevel: 'medium',
    riskScore: 48,
    reason: "Haven't accessed new content in 5 days",
    daysInactive: 5,
    memberSince: '2024-04-18',
    plan: 'Monthly Access',
    planValue: 97,
    lastActivity: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

export const mockChurnEvents: ChurnEvent[] = [
  {
    id: 'c1',
    userId: 'usr_010',
    userName: 'David Kim',
    cancelledAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    plan: 'Elite Mastermind',
    planValue: 297,
    reason: 'Too expensive',
    recoverable: true,
    recoveryAction: 'Offer 30% discount for 3 months',
  },
  {
    id: 'c2',
    userId: 'usr_011',
    userName: 'Emma Clarke',
    cancelledAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    plan: 'Pro Course Bundle',
    planValue: 197,
    reason: 'Not enough time',
    recoverable: true,
    recoveryAction: 'Pause subscription for 1 month',
  },
  {
    id: 'c3',
    userId: 'usr_012',
    userName: 'Ryan Foster',
    cancelledAt: new Date(Date.now() - 86400000).toISOString(),
    plan: 'Monthly Access',
    planValue: 97,
    reason: 'Found alternative',
    recoverable: false,
  },
];

export const mockRevenueRecovery: RevenueRecoveryItem[] = [
  {
    id: 'r1',
    userId: 'usr_020',
    userName: 'Natalie Brooks',
    amount: 297,
    failedAt: new Date(Date.now() - 86400000).toISOString(),
    attempts: 1,
    status: 'recovering',
    nextRetry: new Date(Date.now() + 86400000).toISOString(),
    plan: 'Elite Mastermind',
  },
  {
    id: 'r2',
    userId: 'usr_021',
    userName: 'Omar Hassan',
    amount: 197,
    failedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    attempts: 2,
    status: 'recovering',
    nextRetry: new Date(Date.now() + 2 * 86400000).toISOString(),
    plan: 'Pro Course Bundle',
  },
  {
    id: 'r3',
    userId: 'usr_022',
    userName: 'Isabella Turner',
    amount: 97,
    failedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    attempts: 1,
    status: 'pending',
    nextRetry: new Date(Date.now() + 86400000).toISOString(),
    plan: 'Monthly Access',
  },
  {
    id: 'r4',
    userId: 'usr_023',
    userName: 'Carlos Mendez',
    amount: 297,
    failedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    attempts: 3,
    status: 'recovered',
    plan: 'Elite Mastermind',
  },
  {
    id: 'r5',
    userId: 'usr_024',
    userName: 'Zoe Mitchell',
    amount: 197,
    failedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    attempts: 4,
    status: 'failed',
    plan: 'Pro Course Bundle',
  },
];

export const mockAIInsights: AIInsight[] = [
  {
    id: 'ai1',
    type: 'warning',
    title: 'Churn Spike Detected in Elite Tier',
    description: 'Your Elite Mastermind plan has seen a 34% increase in cancellations over the last 7 days, primarily from members who joined 60-90 days ago.',
    impact: 'high',
    metric: '-$8,910 projected MRR risk',
    suggestion: 'Launch a "90-Day Win" campaign targeting these members with exclusive 1-on-1 content or a bonus module to reinforce value.',
    generatedAt: new Date().toISOString(),
  },
  {
    id: 'ai2',
    type: 'opportunity',
    title: 'Revenue Recovery Window Open',
    description: 'You have 12 failed payments totaling $2,847 that are in the optimal retry window (days 3-5 post-failure have 68% recovery rate).',
    impact: 'high',
    metric: '$2,847 recoverable today',
    suggestion: 'Send a personal email (not automated) to the top 5 highest-value failed payments. Human touch increases recovery by 3x.',
    generatedAt: new Date().toISOString(),
  },
  {
    id: 'ai3',
    type: 'trend',
    title: 'Thursday Engagement Peak Identified',
    description: 'Member engagement is 2.8x higher on Thursday evenings (6-9 PM EST). Your last 3 major announcements missed this window.',
    impact: 'medium',
    metric: '+28% open rate potential',
    suggestion: 'Schedule your next content drop and email blast for Thursday at 7 PM EST. This could add ~340 active sessions.',
    generatedAt: new Date().toISOString(),
  },
  {
    id: 'ai4',
    type: 'action',
    title: 'Upsell Opportunity: 89 Monthly → Annual',
    description: '89 members on your Monthly Access plan have been active for 4+ months with >70% content completion — prime candidates for annual upgrade.',
    impact: 'high',
    metric: '+$52,000 ARR potential',
    suggestion: 'Create a "Founding Annual Member" offer with 2 months free. These members already love your content — just remove the friction.',
    generatedAt: new Date().toISOString(),
  },
];

export const mockRevenueData: RevenueDataPoint[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (29 - i));
  return {
    date: date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
    revenue: Math.floor(3000 + Math.random() * 2500 + i * 80),
    recovered: Math.floor(200 + Math.random() * 800),
    lost: Math.floor(100 + Math.random() * 400),
  };
});

export const mockMemberActivity: MemberActivity[] = Array.from({ length: 14 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (13 - i));
  return {
    date: date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
    newMembers: Math.floor(20 + Math.random() * 40),
    churned: Math.floor(5 + Math.random() * 15),
    active: Math.floor(2600 + Math.random() * 300),
  };
});
